### ISSUE TITLE
Подключение

### ISSUE THREAD

**Issue by itomnov** [DEVTPS/education#1]
нет доступа к репозиторию - вероятно надо добавить меня в члены организации

**Comment by Rombs** [comment]
Хмм... я думал, что создал открытый репозиторий

**Comment by itomnov** [comment]
git -c diff.mnemonicprefix=false -c core.quotepath=false push -v --tags --set-upstream origin master:master
remote: Permission to DEVTPS/education.git denied to itomnov.
fatal: unable to access 'https://github.com/DEVTPS/education.git/': The requested URL returned error: 403

**Comment by Rombs** [comment]
Создал команду TPS Developers.
Дал ей доступ на уровне чтения.
Отправил тебе приглашение

**Comment by itomnov** [comment]
всё ок. но мне кажется я перетер какой-то код который был в <code>. команды, как подключаться, клонировать и т.д. если это так, то это очень серьезный баг.

**Comment by Rombs** [comment]
супер!
Не переживай - ты ничего не перетер!
Чтобы такое сделать - надо оооочень сильно извращаться :)
Обычно создается конфликт, но сейчас такого нет - ты первый, кто закомитил.
Заявку закрываю
